import * as NodeServices from "@effect/platform-node/NodeServices"
import { Effect, FileSystem, ManagedRuntime, Option, Path, Schema } from "effect"

const skillRoot = new URL("../../../skills/noyau/", import.meta.url)
const targetUrl = new URL("../src/agent-skill/generated.ts", import.meta.url)
const paths = [
  "SKILL.md",
  "agents/openai.yaml",
  "references/board-reading.md",
  "references/ticket-lifecycle.md",
  "references/dependencies.md",
  "references/thread-linking.md",
  "references/error-recovery.md",
] as const

const encodeFiles = Schema.encodeEffect(
  Schema.fromJsonString(
    Schema.Array(Schema.Struct({ path: Schema.NonEmptyString, content: Schema.String })),
  ),
)

const generateAgentSkill = Effect.gen(function* () {
  const fileSystem = yield* FileSystem.FileSystem
  const path = yield* Path.Path
  const target = yield* path.fromFileUrl(targetUrl)
  const files = yield* Effect.forEach(paths, (relativePath) =>
    path.fromFileUrl(new URL(relativePath, skillRoot)).pipe(
      Effect.flatMap(fileSystem.readFileString),
      Effect.map((content) => ({ path: relativePath, content })),
    ),
  )
  const encoded = yield* encodeFiles(files)
  const generated = `// Generated by scripts/generate-agent-skill.ts from skills/noyau. Do not edit.\nexport const NOYAU_AGENT_SKILL_FILES = ${encoded} as const\n`
  const current = yield* fileSystem.readFileString(target).pipe(Effect.option)
  if (Option.isNone(current) || current.value !== generated) {
    yield* fileSystem.writeFileString(target, generated)
  }
})

const runtime = ManagedRuntime.make(NodeServices.layer)
void runtime.runPromise(generateAgentSkill)
